check for sonar ninja

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,6 +29,7 @@ jobs:
       run: |
         cmake -S . -B build
         which build-wrapper-linux-x86_64 || echo "failed while looking for wrapper command"
+        which ninja || echo "ninja not found"
         build-wrapper-linux-x86-64 --out-dir cmake-build-sonar ninja -C build || echo "failed to run wrapper command"
     - name: Run sonar-scanner
       run: |
