Update build.yml
simplify sonarcube scanning

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,7 +8,7 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
     - uses: lukka/get-cmake@latest
     - name: cmake
       run: cmake -B cmake-build -S . -GNinja && cmake --build cmake-build
@@ -26,3 +26,11 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+    - name: Run build-wrapper
+      run: |
+        cmake -S . -B build
+        which build-wrapper-linux-x86_64 || echo "failed while looking for wrapper command"
+        which ninja || echo "ninja not found"
+        build-wrapper-linux-x86-64 --out-dir cmake-build-sonar cmake --build build || echo "failed to run wrapper command"
+    - name: run tox
+      run: python3 -m pip install tox && tox -e py
